### ISSUE TITLE
Change name to SublimeLinter-contrib-modelsim

### ISSUE THREAD

**Issue by jevogel** [jevogel/SublimeLinter-contrib-modelsim#2]
Change name to SublimeLinter-contrib-modelsim, or something similar.
Now that the plugin supports both `vcom` and `vlog` the name should reflect that in some way.

**Comment by vengin** [comment]
@jevogel, correct me if I am wrong, but you should be able to rename the repository (as it's owner).
[Renaming a repository](https://help.github.com/articles/renaming-a-repository/)

**Comment by jevogel** [comment]
Okay, I'll change the name of the repo and then update the package control repo [here](https://github.com/SublimeLinter/package_control_channel). We may have to remove the old package and install the new one.

**Comment by vengin** [comment]
BTW, the initial header in the [Readme.md, line1](https://github.com/jevogel/SublimeLinter-contrib-modelsim/blob/master/README.md) is still **SublimeLinter-contrib-vcom** (not -modelsim or whatever other name will be used for the package).

**Comment by jevogel** [comment]
Fixed that, thanks.

**Comment by jevogel** [comment]
Plugin is officially renamed in the package control repo. Closing.

https://github.com/SublimeLinter/package_control_channel/pull/72#event-1955254630
